import { UserProvider } from "@auth0/nextjs-auth0/client";
import { withPageAuthRequired } from "@auth0/nextjs-auth0";
import Header from "../../components/header/Header";
import Footer from "../../components/footer/Footer";
import { ThemeProvider } from "../../provider/ThemeProvider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "ka" }];
}

function RootLayout({ children, params }) {
  return (
    <html lang={params.lang}>
      <body className="flex flex-col justify-between font-sans transition-colors duration-300 bg-black text-white dark:bg-black dark:text-white">
        <UserProvider>
          <ThemeProvider>
            <Header />
            {children}
            <Footer />
          </ThemeProvider>
        </UserProvider>
      </body>
    </html>
  );
}

export default withPageAuthRequired(RootLayout);
